<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Platforms>x64;arm64</Platforms>
		<RuntimeIdentifiers>win-x64;win-arm64;osx-arm64</RuntimeIdentifiers>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<IncludeAvaloniaGenerators>true</IncludeAvaloniaGenerators>
		<ApplicationIcon>Assets\Icon.ico</ApplicationIcon>
		<Version>1.0.0-nightly.0</Version>
		<AssemblyVersion>1.0.0</AssemblyVersion>
		<AssemblyTitle>naget</AssemblyTitle>
		<AssemblyName>naget</AssemblyName>
		<Product>naget</Product>
		<Company>Milkeyyy</Company>
		<Copyright>Copyright (C) 2026 Milkeyyy</Copyright>
		<Description>naget</Description>
	</PropertyGroup>

	<PropertyGroup>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>

	<PropertyGroup>
		<InvariantGlobalization>true</InvariantGlobalization>
		<PredefinedCulturesOnly>false</PredefinedCulturesOnly>
	</PropertyGroup>

	<!-- 単一ファイル化 & ファイルサイズ削減 & 圧縮 -->
	<PropertyGroup>
		<DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
	</PropertyGroup>
	<PropertyGroup Label="Avalonia">
		<AvaloniaNameGeneratorAttachDevTools Condition="'$(Configuration)' == 'Debug'">True</AvaloniaNameGeneratorAttachDevTools>
		<Title>$(AssemblyName)</Title>
		<FileVersion></FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Remove="Assets\Locales\Resources.ja-JP.resx" />
		<AvaloniaResource Remove="Assets\Locales\Resources.resx" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\Icon.ico" />
		<EmbeddedResource Include="build.json" />
		<EmbeddedResource Include="library.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.0.0-preview2" />
		<PackageReference Include="Avalonia.Controls.WebView" Version="12.0.0-preview2" />
		<PackageReference Include="Avalonia.Desktop" Version="12.0.0-preview2" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<!--<PackageReference Include="Avalonia.Diagnostics" Version="11.0.13">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>none</IncludeAssets>
		</PackageReference>-->
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.1.1" Condition="'$(Configuration)' == 'Debug'" />
		<PackageReference Include="Dotnet.Bundle" Version="0.9.13" />
		<PackageReference Include="Epoxy.Avalonia11" Version="1.16.0" />
		<PackageReference Include="FluentAvaloniaUI" Version="2.5.0" />
		<!-- <PackageReference Include="FluentIcons.Avalonia.Fluent" Version="1.2.315" /> -->
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
		<PackageReference Include="Velopack" Version="0.0.1298" />
		<PackageReference Include="roslynator.analyzers" Version="4.15.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="SharpHook" Version="7.1.1" />
		<PackageReference Include="System.Text.Json" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Assets\Locales\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="Views\UpdateCompleteWindow.axaml.cs">
			<DependentUpon>UpdateCompleteWindow.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\BrowserWindow.axaml.cs">
			<DependentUpon>BrowserWindow.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\AboutWindow.axaml.cs">
			<DependentUpon>AboutWindow.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Dialog\InputDialogContent.axaml.cs">
			<DependentUpon>InputDialogContent.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Settings\AppSettingsView.axaml.cs">
			<DependentUpon>AppSettingsView.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Settings\SearchEngineDialogContent.axaml.cs">
			<DependentUpon>SearchEngineDialogContent.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Settings\ShortcutKeyPresetCreator.axaml.cs">
			<DependentUpon>ShortcutKeyPresetCreator.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Settings\InAppBrowserView.axaml.cs">
			<DependentUpon>InAppBrowserView.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Settings\ShortcutKeyView.axaml.cs">
			<DependentUpon>ShortcutKeyView.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Settings\SearchView.axaml.cs">
			<DependentUpon>SearchView.axaml</DependentUpon>
		</Compile>
		<EmbeddedResource Update="Assets\Locales\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Assets\Fonts\" />
	</ItemGroup>
</Project>
