//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchLight.Assets.Locales {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchLight.Assets.Locales.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SearchLight に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Design に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Design {
            get {
                return ResourceManager.GetString("Settings.Tab.Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In App Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_InAppBrowser {
            get {
                return ResourceManager.GetString("Settings.Tab.InAppBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Search {
            get {
                return ResourceManager.GetString("Settings.Tab.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_ShortcutKey {
            get {
                return ResourceManager.GetString("Settings.Tab.ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_System {
            get {
                return ResourceManager.GetString("Settings.Tab.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Update {
            get {
                return ResourceManager.GetString("Settings.Tab.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenu_Exit {
            get {
                return ResourceManager.GetString("TrayMenu.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In App Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenu_InAppBrowser {
            get {
                return ResourceManager.GetString("TrayMenu.InAppBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenu_Settings {
            get {
                return ResourceManager.GetString("TrayMenu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Copy {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Cut {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Delete {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Paste {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Redo {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_SelectAll {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Undo {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_Navigation_Back {
            get {
                return ResourceManager.GetString("WebBrowser.Navigation.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_Navigation_Forward {
            get {
                return ResourceManager.GetString("WebBrowser.Navigation.Forward", resourceCulture);
            }
        }
    }
}
