//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace naget.Assets.Locales {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("naget.Assets.Locales.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   naget に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Dialog.Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Button_Close {
            get {
                return ResourceManager.GetString("Dialog.Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Button_No {
            get {
                return ResourceManager.GetString("Dialog.Button.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Button_Yes {
            get {
                return ResourceManager.GetString("Dialog.Button.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Design_Theme {
            get {
                return ResourceManager.GetString("Settings.Design.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Design_Theme_Name_Dark {
            get {
                return ResourceManager.GetString("Settings.Design.Theme.Name.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Design_Theme_Name_Default {
            get {
                return ResourceManager.GetString("Settings.Design.Theme.Name.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Design_Theme_Name_Light {
            get {
                return ResourceManager.GetString("Settings.Design.Theme.Name.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_InAppBrowser_StartPage {
            get {
                return ResourceManager.GetString("Settings.InAppBrowser.StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_Add {
            get {
                return ResourceManager.GetString("Settings.Search.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_Delete {
            get {
                return ResourceManager.GetString("Settings.Search.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_Edit {
            get {
                return ResourceManager.GetString("Settings.Search.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Engine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_SearchEngine {
            get {
                return ResourceManager.GetString("Settings.Search.SearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Search Engine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_SearchEngine_Dialog_Add {
            get {
                return ResourceManager.GetString("Settings.Search.SearchEngine.Dialog.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There must be at least one search engine. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_SearchEngine_Dialog_Delete_CannotDelete_Description {
            get {
                return ResourceManager.GetString("Settings.Search.SearchEngine.Dialog.Delete.CannotDelete.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This search engine cannot be deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_SearchEngine_Dialog_Delete_CannotDelete_Title {
            get {
                return ResourceManager.GetString("Settings.Search.SearchEngine.Dialog.Delete.CannotDelete.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_SearchEngine_Dialog_Delete_Confirm {
            get {
                return ResourceManager.GetString("Settings.Search.SearchEngine.Dialog.Delete.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete search engine &quot;{0}&quot;? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_SearchEngine_Dialog_Delete_Description {
            get {
                return ResourceManager.GetString("Settings.Search.SearchEngine.Dialog.Delete.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Search Engine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_SearchEngine_Dialog_Delete_Title {
            get {
                return ResourceManager.GetString("Settings.Search.SearchEngine.Dialog.Delete.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Search Engine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_SearchEngine_Dialog_Edit {
            get {
                return ResourceManager.GetString("Settings.Search.SearchEngine.Dialog.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_SearchEngine_Dialog_Name {
            get {
                return ResourceManager.GetString("Settings.Search.SearchEngine.Dialog.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Search_SearchEngine_Dialog_Url {
            get {
                return ResourceManager.GetString("Settings.Search.SearchEngine.Dialog.Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Action {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Action_None {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Action.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Action_WebSearch {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Action.WebSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Engine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Action_WebSearch_SearchEngine {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Action.WebSearch.SearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Key {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifier Keys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_ModifierKeys {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.ModifierKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset_Create {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create New Preset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset_CreateNewPreset {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset.CreateNewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset_Dialog_Delete_Confirm {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset.Dialog.Delete.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete preset &quot;{0}&quot;? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset_Dialog_Delete_Description {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset.Dialog.Delete.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Preset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset_Dialog_Delete_Title {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset.Dialog.Delete.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset_Dialog_Rename_InputTitle {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset.Dialog.Rename.InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name is Empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset_Dialog_Rename_NameIsEmpty {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset.Dialog.Rename.NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Preset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset_Dialog_Rename_Title {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset.Dialog.Rename.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name is Empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset_NameIsEmpty {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset.NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_Preset_NotSet {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.Preset.NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_RegisterKeys_Done {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.RegisterKeys.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press Esc to Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_RegisterKeys_PressEscToCancel {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.RegisterKeys.PressEscToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey_RegisterKeys_Register {
            get {
                return ResourceManager.GetString("Settings.ShortcutKey.RegisterKeys.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_System_Language {
            get {
                return ResourceManager.GetString("Settings.System.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You need to restart the application for the settings to take effect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_System_Language_RequiredRestart {
            get {
                return ResourceManager.GetString("Settings.System.Language.RequiredRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart the Application to Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_System_Language_RestartApplication {
            get {
                return ResourceManager.GetString("Settings.System.Language.RestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_AppSettings {
            get {
                return ResourceManager.GetString("Settings.Tab.AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Design に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Design {
            get {
                return ResourceManager.GetString("Settings.Tab.Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In App Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_InAppBrowser {
            get {
                return ResourceManager.GetString("Settings.Tab.InAppBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Search {
            get {
                return ResourceManager.GetString("Settings.Tab.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_ShortcutKey {
            get {
                return ResourceManager.GetString("Settings.Tab.ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_System {
            get {
                return ResourceManager.GetString("Settings.Tab.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Update {
            get {
                return ResourceManager.GetString("Settings.Tab.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Update_Check {
            get {
                return ResourceManager.GetString("Settings.Update.Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Update_CheckUpdate {
            get {
                return ResourceManager.GetString("Settings.Update.CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Strings_Cancel {
            get {
                return ResourceManager.GetString("Strings.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Strings_Ok {
            get {
                return ResourceManager.GetString("Strings.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenu_CheckUpdate {
            get {
                return ResourceManager.GetString("TrayMenu.CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenu_Exit {
            get {
                return ResourceManager.GetString("TrayMenu.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In App Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenu_InAppBrowser {
            get {
                return ResourceManager.GetString("TrayMenu.InAppBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrayMenu_Settings {
            get {
                return ResourceManager.GetString("TrayMenu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress - {0} % に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_Download_Downloading_Description {
            get {
                return ResourceManager.GetString("Updater.Dialog.Download.Downloading.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading Update File... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_Download_Downloading_Title {
            get {
                return ResourceManager.GetString("Updater.Dialog.Download.Downloading.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to download update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_Download_Failed_Description {
            get {
                return ResourceManager.GetString("Updater.Dialog.Download.Failed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_Download_Failed_Title {
            get {
                return ResourceManager.GetString("Updater.Dialog.Download.Failed.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installation will begin in 5 seconds... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_Download_Install_Description {
            get {
                return ResourceManager.GetString("Updater.Dialog.Download.Install.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_Download_Install_Title {
            get {
                return ResourceManager.GetString("Updater.Dialog.Download.Install.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A new version of naget has been released!
        ///Would you like to update? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_UpdateAvailable_Description {
            get {
                return ResourceManager.GetString("Updater.Dialog.UpdateAvailable.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Available! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_UpdateAvailable_Title {
            get {
                return ResourceManager.GetString("Updater.Dialog.UpdateAvailable.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Version: {0}
        ///Latest Version: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_UpdateAvailable_VersionInfo {
            get {
                return ResourceManager.GetString("Updater.Dialog.UpdateAvailable.VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The latest version ({0}) is already installed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_UpdateNotAvailable_Description {
            get {
                return ResourceManager.GetString("Updater.Dialog.UpdateNotAvailable.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest Version is Installed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Dialog_UpdateNotAvailable_Title {
            get {
                return ResourceManager.GetString("Updater.Dialog.UpdateNotAvailable.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Copy {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Cut {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Delete {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Paste {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Redo {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_SelectAll {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_ContextMenu_Undo {
            get {
                return ResourceManager.GetString("WebBrowser.ContextMenu.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_NativeMenu_Edit {
            get {
                return ResourceManager.GetString("WebBrowser.NativeMenu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navigate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_NativeMenu_Navigate {
            get {
                return ResourceManager.GetString("WebBrowser.NativeMenu.Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_Navigation_Back {
            get {
                return ResourceManager.GetString("WebBrowser.Navigation.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebBrowser_Navigation_Forward {
            get {
                return ResourceManager.GetString("WebBrowser.Navigation.Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window_InAppBrowser {
            get {
                return ResourceManager.GetString("Window.InAppBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window_Settings {
            get {
                return ResourceManager.GetString("Window.Settings", resourceCulture);
            }
        }
    }
}
