name: Build Nightly

on:
  push:
    branches: [ "dev" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        os: [ 'win' ]
        arch: [ 'x64', 'arm64' ]
        runner: [ 'windows-latest' ]
        include:
          - os: osx
            arch: arm64
            runner: macos-latest

    runs-on: ${{ matrix.runner }}

    permissions:
      contents: write

    env:
      rid: ${{ matrix.os }}-${{ matrix.arch }}
      OUTPUT_DIR: ./_Pack
      VelopackChannel: ${{ matrix.os }}-${{ matrix.arch }}-nightly

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Create Directory
      shell: pwsh
      run: New-Item -ItemType Directory -ErrorAction SilentlyContinue ${{ env.OUTPUT_DIR }}/${{ env.rid }}

    - name: Load Build Info
      shell: pwsh
      run: |
        python -c 'print("COMMIT_HASH_SHORT=" + ("${{ github.sha }}"[0:7]))' >> $env:GITHUB_ENV


    # ビルド (Windows)
    - if: ${{ startsWith(env.rid, 'win') }}
      name: Build
      run: ./build.cmd --runtime ${{ env.rid }} --releasechannel nightly --releasenumber ${{ env.COMMIT_HASH_SHORT }}

    # ビルド (macOS)
    - if: ${{ startsWith(env.rid, 'osx') }}
      name: Build
      run: ./build.sh --runtime ${{ env.rid }} --releasechannel nightly --releasenumber ${{ env.COMMIT_HASH_SHORT }}


    - name: Load Full Version
      shell: pwsh
      run: |
        $buildInfo = (Get-Content "./naget/build.json" | ConvertFrom-Json)
        echo "APP_FULL_VERSION=$($buildInfo.full_version)" >> $env:GITHUB_ENV


    - name: Install vpk
      continue-on-error: true
      run: dotnet tool install -g vpk

    - name: Create Releases Directory
      shell: pwsh
      run: New-Item -ItemType Directory -ErrorAction SilentlyContinue "${{ env.OUTPUT_DIR }}/${{ env.rid }}/Releases"

    - name: Download Previous Release
      working-directory: ${{ env.OUTPUT_DIR }}/${{ env.rid }}
      continue-on-error: true
      run: vpk download github --repoUrl https://github.com/Milkeyyy/naget --channel ${{ env.VelopackChannel }} --token ${{ secrets.GITHUB_TOKEN }} --pre -o ./Releases

    # パック (Windows)
    - if: ${{ startsWith(env.rid, 'win') }}
      name: Pack
      working-directory: ${{ env.OUTPUT_DIR }}/${{ env.rid }}
      run: vpk pack -u naget -v ${{ env.APP_FULL_VERSION }} -p ./Build -o ./Releases -e naget.exe --channel ${{ env.VelopackChannel }} --packAuthors Milkeyyy -i ../../Logo/naget.ico --noPortable

    # パック (macOS)
    - if: ${{ startsWith(env.rid, 'osx') }}
      name: Pack
      working-directory: ${{ env.OUTPUT_DIR }}/${{ env.rid }}
      run: vpk pack -u naget -v ${{ env.APP_FULL_VERSION }} -p ./Build -o ./Releases -e naget --channel ${{ env.VelopackChannel }} --packAuthors Milkeyyy -i ../../Logo/naget.icns

    - name: Upload to GitHub
      working-directory: ${{ env.OUTPUT_DIR }}/${{ env.rid }}
      run: vpk upload github --repoUrl https://github.com/Milkeyyy/naget --channel ${{ env.VelopackChannel }} --token ${{ secrets.GITHUB_TOKEN }} --tag nightly --targetCommitish update --releaseName "Nightly Build" --pre --merge --publish -o ./Releases
