name: Test

on: [ workflow_dispatch ]

jobs:
  update-nightly-releases:
    name: Update Nightly Releases
    runs-on: windows-latest

    steps:
      - name: Generate GitHub Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.RELEASES_REPO_APP_ID }}
          private-key: ${{ secrets.RELEASES_REPO_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            naget-Releases

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
